#!/bin/sh 
#SBATCH --job-name=cellranger 
#SBATCH --partition=highmem2new
#SBATCH --nodes=1 
#SBATCH --time=4-0 
#SBATCH --mem=250G 
#SBATCH --ntasks=16 
#SBATCH --error=job.%J.err 
#SBATCH --out=job.%J.out 

/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/bin/cellranger-atac count --id=ME11_FKDL230197201-1a \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/reference_genomes/refdata-cellranger-arc-mm10-2020-A-2.0.0 \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/IMPORTANT_DATA_DONT_DELETE/X204SC23073527-Z01-F003/01.RawData/A_ME11 \
                                                                                       --sample=FKDL230197201-1a \
                                                                                       --localcores=16 \
                                                                                       --localmem=248
/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/bin/cellranger-atac count --id=ME8_FKDL230197198-1a \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/reference_genomes/refdata-cellranger-arc-mm10-2020-A-2.0.0 \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/IMPORTANT_DATA_DONT_DELETE/X204SC23073527-Z01-F003/01.RawData/A_ME8 \
                                                                                       --sample=FKDL230197198-1a \
                                                                                       --localcores=16 \
                                                                                       --localmem=248
/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/bin/cellranger-atac count --id=ME9_FKDL230197199-1a \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/reference_genomes/refdata-cellranger-arc-mm10-2020-A-2.0.0 \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/IMPORTANT_DATA_DONT_DELETE/X204SC23073527-Z01-F003/01.RawData/A_ME9 \
                                                                                       --sample=FKDL230197199-1a \
                                                                                       --localcores=16 \
                                                                                       --localmem=248
/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/bin/cellranger-atac count --id=ME10_FKDL230197200-1a \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/reference_genomes/refdata-cellranger-arc-mm10-2020-A-2.0.0 \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/IMPORTANT_DATA_DONT_DELETE/X204SC23073527-Z01-F003/01.RawData/A_ME10 \
                                                                                       --sample=FKDL230197200-1a \
                                                                                       --localcores=16 \
                                                                                       --localmem=248
