#!/bin/sh 
#SBATCH --job-name=cellranger 
#SBATCH --partition=fast
#SBATCH --nodes=1 
#SBATCH --time=3-0
#SBATCH --mem=120G
#SBATCH --ntasks=16 
#SBATCH --error=job.%J.err 
#SBATCH --out=job.%J.out 

# /groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/bin/cellranger-atac count --id=A_RE8 \
#                                                                                        --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/reference_genomes/Rattus_norvegicus.GRCr8/GRCr8 \
#                                                                                        --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/sequencing_results/sc_atacseq/rat/ \
#                                                                                        --sample=A_RE8 \
#                                                                                        --localcores=14 \
#                                                                                        --localmem=115
# /groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/bin/cellranger-atac count --id=A_RE9 \
#                                                                                        --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/reference_genomes/Rattus_norvegicus.GRCr8/GRCr8 \
#                                                                                        --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/sequencing_results/sc_atacseq/rat/ \
#                                                                                        --sample=A_RE9 \
#                                                                                        --localcores=14 \
#                                                                                        --localmem=115
# /groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/bin/cellranger-atac count --id=A_RE10 \
#                                                                                        --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/reference_genomes/Rattus_norvegicus.GRCr8/GRCr8 \
#                                                                                        --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/sequencing_results/sc_atacseq/rat/ \
#                                                                                        --sample=A_RE10 \
#                                                                                        --localcores=14 \
#                                                                                        --localmem=115
# /groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/bin/cellranger-atac count --id=A_RE11 \
#                                                                                        --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/reference_genomes/Rattus_norvegicus.GRCr8/GRCr8 \
#                                                                                        --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/sequencing_results/sc_atacseq/rat/ \
#                                                                                        --sample=A_RE11 \
#                                                                                        --localcores=14 \
#                                                                                        --localmem=115
/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/bin/cellranger-atac count --id=A_RE12 \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/cellranger_related/cellranger-atac-2.1.0/reference_genomes/Rattus_norvegicus.GRCr8/GRCr8 \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/4_species_project/sequencing_results/sc_atacseq/rat/ \
                                                                                       --sample=A_RE12 \
                                                                                       --localcores=14 \
                                                                                       --localmem=115
