#!/bin/sh 
#SBATCH --job-name=cellranger 
#SBATCH --partition=highmem2new
#SBATCH --nodes=1 
#SBATCH --time=4-0 
#SBATCH --mem=250G 
#SBATCH --ntasks=16 
#SBATCH --error=job.%J.err 
#SBATCH --out=job.%J.out 

/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/bin/cellranger-atac count --id=CkD1_FKDL230197203-1a \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/reference_genomes/Gallus_gallus.bGalGal1.mat.broiler.GRCg7b/GRCg7b/ \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/IMPORTANT_DATA_DONT_DELETE/X204SC23073527-Z01-F003/01.RawData/A_CkD1 \
                                                                                       --sample=FKDL230197203-1a \
                                                                                       --localcores=16 \
                                                                                       --localmem=248
/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/bin/cellranger-atac count --id=CkD2_FKDL230197204-1a \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/reference_genomes/Gallus_gallus.bGalGal1.mat.broiler.GRCg7b/GRCg7b/ \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/IMPORTANT_DATA_DONT_DELETE/X204SC23073527-Z01-F003/01.RawData/A_CkD2 \
                                                                                       --sample=FKDL230197204-1a\
                                                                                       --localcores=16 \
                                                                                       --localmem=248
/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/bin/cellranger-atac count --id=CkD3_FKDL230197205-1a \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/reference_genomes/Gallus_gallus.bGalGal1.mat.broiler.GRCg7b/GRCg7b/ \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/IMPORTANT_DATA_DONT_DELETE/X204SC23073527-Z01-F003/01.RawData/A_CkD3 \
                                                                                       --sample=FKDL230197205-1a \
                                                                                       --localcores=16 \
                                                                                       --localmem=248
/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/bin/cellranger-atac count --id=CkD4_FKDL230197206-1a \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/reference_genomes/Gallus_gallus.bGalGal1.mat.broiler.GRCg7b/GRCg7b/ \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/IMPORTANT_DATA_DONT_DELETE/X204SC23073527-Z01-F003/01.RawData/A_CkD4 \
                                                                                       --sample=FKDL230197206-1a \
                                                                                       --localcores=16 \
                                                                                       --localmem=248
/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/bin/cellranger-atac count --id=CkD5_FKDL230197207-1a \
                                                                                       --reference=/groups/mpistaff/Cranio_Lab/Louk_Seton/cellranger-atac-2.1.0/reference_genomes/Gallus_gallus.bGalGal1.mat.broiler.GRCg7b/GRCg7b/ \
                                                                                       --fastqs=/groups/mpistaff/Cranio_Lab/Louk_Seton/IMPORTANT_DATA_DONT_DELETE/X204SC23073527-Z01-F003/01.RawData/A_CkD5 \
                                                                                       --sample=FKDL230197207-1a \
                                                                                       --localcores=16 \
                                                                                       --localmem=248
